### ISSUE TITLE
Questions about documentation in README.md

### ISSUE THREAD

**Issue by alexislefebvre** [jcalderonzumba/MinkPhantomJSDriver#73]
I don't understand an explanation and some YAML excerpts in [README.md](https://github.com/jcalderonzumba/MinkPhantomJSDriver/blob/6e4a8c7901e2e3bf319b5272103bc50283c8df42/README.md#how-to-use).

---

It is written *Extension configuration (for the moment NONE).*. Should we copy-paste the configuration if there is no configuration yet?

---

The following code appear:

```yml
default:
  extensions:
    Zumba\PhantomJSExtension:
```

This is not a valid YAML file. It may be `Zumba\PhantomJSExtension: ~` to avoid a YAML error.

---

```yaml
Behat\MinkExtension:
phantomjs:
    phantom_server: "http://localhost:8510/api"
    template_cache: "/tmp/pjsdrivercache/phantomjs"
```

It looks like some indentations are missing in this excerpt. Is `phantomjs:` as sub-node of `Behat\MinkExtension:`? Is `Behat\MinkExtension:` a sub-node of `default.extensions`?
